dataset:
  name: "sentence-transformers/amazon-reviews"
  split: "train"
  size: 400000
  output_dir: "data/raw"
  output_file: "amazon_review_subset.jsonl.gz"
  num_log_steps: 1000000
  seed: 42

cleaning:
  source_file: "data/raw/amazon_review_subset.jsonl.gz"
  min_review_length: 30
  min_summary_length: 10
  max_summary_length: 200
  bad_summaries: ["good", "ok", "nice", "great", "bad", "fine", "yes"]
  output_dir: "data/processed"
  output_file: "amazon_review_subset_cleaned.jsonl"

partition:
  source_file: "data/processed/amazon_review_subset_cleaned.jsonl"
  seed: 42
  split_ratio:
    train: 0.8
    val: 0.1
    test: 0.1
  output_dir: "data/split"
  out_files:
    train: "train.jsonl"
    val: "val.jsonl"
    test: "test.jsonl"


