stage: "dpo"

data:
  preference_file: "data/preferences/pairs.jsonl"

model:
  input_checkpoint: "m/content/drive/MyDrive/amazon_project/checkpoints/sft"
  base_model: "facebook/bart-base"

train:
  epochs: 2
  batch_size: 4
  learning_rate: 1e-5
  beta: 0.1
  eval_steps: 500
  save_steps: 1000
output:
  dir: "/content/drive/MyDrive/amazon_project/checkpoints/dpo"
