stage: "sft"
seed: 42

data:
  train_set: "data/split/train_20k.jsonl"
  val_set: "data/split/val.jsonl"

model:
  base_model: "facebook/bart-base"
  tokenizer: "facebook/bart-base"
  max_input_len: 224     
  max_output_len: 64

train:
  checkpoint_dir: "checkpoints/sft"
  epochs: 3
  batch_size: 8
  gradient_accumulation_steps: 4
  # learning_rate: 3e-5
  learning_rate: 0.00003
  max_length: 256
  eval_steps: 200
  save_steps: 200
  logging_steps: 100
  evaluation_strategy: "steps"
  report_to: ["tensorboard"]
  metrics: ["rouge"]
  early_stopping:
    enabled: true
    patience: 2
    metric: "eval_rougeL"        # or eval_loss
    mode: "max"                  

output:
  dir_colab: "/content/drive/MyDrive/amazon_review_RLHF/models/sft"
  dir_local: "models/sft"